version: '3'
services:
  postgres:
    image: postgres:13
    restart: always
    ports:
    - "5432:5432"
    environment:
      PGPORT: '5432'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  # command to list volumes: docker volume ls
  # command to delete volumes: docker volume rm <volume_name>
  # but usually you'll need to do docker compose down first.
  # so `docker compose down && docker volume rm pgkit_postgres` should do the trick.
  postgres:
