name: publish
on: 
  workflow_dispatch:
    inputs:
      changes_hash:
        description: Hash of expected changes from lerna publish. Get this by running `yarn lerna:changes:hash` locally or running this job with no input and copy-pasting the expected value from the error message.

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_CI_TOKEN }}
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: setup/install/build
      run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"

        yarn
        yarn build

        echo '//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}' > ~/.npmrc
    - name: publish
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        GH_TOKEN: ${{ secrets.GH_CI_TOKEN }}
      run: |
        npm whoami | grep .

        EXPECTED_CHANGES=$(yarn --silent lerna:changes:hash)
        if [ "$EXPECTED_CHANGES" != "${{ github.events.inputs.changes_hash }}" ]; then
          echo "Expected hashed changes: $EXPECTED_CHANGES"
          echo "Got: ${{ github.events.inputs.changes_hash }}"
          exit 1
        fi

        echo 'skipping actual publish for now' # yarn lerna publish --yes
